### ISSUE TITLE
More text in route

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#134]
Add more text in each route. 

It should clear example what the route does and what the extra variables do

**Comment by peterdudfield** [comment]
Could be done both by @dctanner and @rachel-labri-tipton

**Comment by rachel-labri-tipton** [comment]
Thanks. Are these the route descriptions found [here](https://api-dev.nowcasting.io/docs#/)? 

I'll try to have a look at the current route descriptions before our check-in tomorrow. 

@dctanner, let me know if you have a moment this week to look at this together.

**Comment by peterdudfield** [comment]
Thanks @rachel-labri-tipton . They are all in the code, but there's a nice way to see them. 

Go to the [api docs](https://api-dev.nowcasting.io/docs#/default/get_forecasts_for_a_specific_gsp_v0_GB_solar_gsp_forecast_one_gsp__gsp_id__get)
Which look a bit like this

![Screenshot 2022-09-06 at 12 04 47](https://user-images.githubusercontent.com/34686298/188619708-9ce0d43d-491c-403d-8e55-89b6c28cb295.png)

**Comment by peterdudfield** [comment]
context: https://github.com/openclimatefix/nowcasting_api/issues/131

**Comment by peterdudfield** [comment]
General info is [here](https://github.com/openclimatefix/nowcasting_api/blob/main/src/main.py#L22) 

each route info is [here](https://github.com/openclimatefix/nowcasting_api/blob/main/src/gsp.py#L50)

**Comment by peterdudfield** [comment]
using pydoc google style https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by peterdudfield** [comment]
I have discussed this with @rachel-labri-tipton (thanks) and she is going to have a go at this. I'm happy to help support with any things that dont make sense. 

We also found a nice thing where you can write 'markdown' code into the descriptions. This helps make formating things really nice

**Comment by rachel-labri-tipton** [comment]
hi @peterdudfield, if you by chance have a moment today, would you be able to add/invite me to this repository? I'm trying to push to the new branch I created, and it says permission denied. Thanks!

**Comment by peterdudfield** [comment]
hi @rachel-labri-tipton . I've invited you to the repo, so hopefully you can do a new branch
