### ISSUE TITLE
Add pylinter

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#15]
## Detailed Description
Good to add auto .giuthub that checks pylinter

## Context
useful to have general way to do this

## Possible Implementation
https://github.com/openclimatefix/nowcasting_utils/blob/main/.github/workflows/linters.yaml

**Comment by OBITORASU** [comment]
So we are supposed to add a linting workflow specifically using pylinter right?

**Comment by peterdudfield** [comment]
Hi @OBITORASU , thanks getting in touch. 
Yes, that would be great! See the example from 'nowcasting_utils' above. 

Would you be able to help out with that? 

Thanks

**Comment by OBITORASU** [comment]
I will drop a PR if I manage to get this working.

**Comment by peterdudfield** [comment]
Amazing, thank you @OBITORASU

**Comment by peterdudfield** [comment]
@all-contributors please add @OBITORASU  for code
