### ISSUE TITLE
get all pvlive gsp values

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#168]
## Detailed Description
Good to get all gsp pvlive values in one api hit. This will be useful for Delta view

## Context
- currently you can only get one gsp value at a time,

## Possible Implementation
- similar to /v0/solar/GB/gsp/pvlive/{gsp_id}, but have /v0/solar/GB/gsp/pvlive/all

**Comment by braddf** [comment]
Yeah I would agree I think... Option 2 would be less client-side looping, and hopefully worth differentiating from/diverging from format of other return objects? Let's go with 2, thanks 👍

**Comment by peterdudfield** [comment]
@braddf Did you want it always return 
1.`in-day` or `day-after` 
2. if no regime is given, then return 'day-after', if no 'day-after' then return 'in-day'

**Comment by braddf** [comment]
Always return one of them would be great, then Typescript won't be unhappy 😄
