### ISSUE TITLE
Performance bottleneck due to auth pattern

### ISSUE THREAD

**Issue by dorinclisu** [openclimatefix/nowcasting_api#176]
I am the author of fastapi_auth0 and I was just having a quick look on the dependency graph, to see how others are using this library.

One thing that quickly got my attention is https://github.com/openclimatefix/nowcasting_api/blob/main/src/auth_utils.py

More specifically, the fact that `get_auth()` is called every time with `get_user()` (which is called for every endpoint request). The problem is that `get_auth()` instantiates an `Auth0` object every time, which involves a lot of initialization code, and - likely the slowest of all - a http request to auth0.com to retrieve the public key. The result is that endpoints protected with this auth will execute unnecessarily slow. 

My suggestion is to instantiate `Auth0` outside of the endpoint function chain, so that it can be reused for all requests.

**Comment by peterdudfield** [comment]
Thanks @dorinclisu for this. I appreciate that, and I can move it outside the function

**Comment by dorinclisu** [comment]
Yep, looks good now.

**Comment by peterdudfield** [comment]
@all-contributors please add @dorinclisu  for review
