### ISSUE TITLE
Struggling to Retrieve Access Token

### ISSUE THREAD

**Issue by AyrtonDare** [openclimatefix/nowcasting_api#216]
## Describe the bug
Unable to retrieve access token from API, failing to resolve the url

## To Reproduce
I'm following the [API access guide](https://openclimatefix.notion.site/API-Access-2d8d2f64215d4432be830cbcc9220012) on Notion which provides the following snippet for retrieving the access token

```bash
export AUTH=$(curl --request POST \
   --url https://nowcasting-pro.eu.auth0.com/oauth/token \
   --header 'content-type: application/json' \
   --data '{"client_id":"QLMdXCCHMS9Zl5W2tDG3otpdcY7GeEnJ", "audience":"https://api.nowcasting.io/", "grant_type":"password", "username":"*********", "password":"************"}'
)
```

The error I get back is: `Could not resolve host: nowcasting-pro.eu.auth0.com`

## Additional context
I have also tried to retrieve the token with Python and got the same result. I can access the GUI ok

**Comment by peterdudfield** [comment]
Hi @AyrtonDare , can you log in to the App with your log in details? 

Are you still having this problem?

**Comment by peterdudfield** [comment]
And did Fraser manage to log in using the API?

**Comment by peterdudfield** [comment]
And I just tried locally with my `username` and `password` and for a bearer token back

**Comment by AyrtonDare** [comment]
We can both log in to the app with no problems, but neither of us have been able to access the API

**Comment by peterdudfield** [comment]
> We can both log in to the app with no problems, but neither of us have been able to access the API

Sorry about this, lets try to sort this, I;ve written to you on Slack

**Comment by peterdudfield** [comment]
Turned out to be an issue with Dare's VPN. @AyrtonDare you happy for me to close this issue?

**Comment by AyrtonDare** [comment]
Yes thank you!
