### ISSUE TITLE
Docker file

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#4]
1. Add docker file for this app to run

2. Add automatic github action that builds docker file every push (move to https://github.com/openclimatefix/nowcasting_api/issues/7)

## Context
This will be useful for in order to deploy it

## Possible Implementation
https://fastapi.tiangolo.com/deployment/docker/

**Comment by mdfaisal98** [comment]
Hi @peterdudfield , I'm new to open source contribution and would like to work on creating the dockerfile for this issue. Could you assign it to me?

**Comment by peterdudfield** [comment]
Hi @mdfaisal98, that would be great if you can help out - Thank you

**Comment by mdfaisal98** [comment]
I have created the dockerfile and docker-compose.yml and tested locally. Let me know if there are any changes regarding the docker image or anything else to create a PR for it. @peterdudfield 
https://github.com/mdfaisal98/nowcasting_api/commit/92217505a1e4e8db2b02cf5dcc321c4c04bd7a37

**Comment by jacobbieker** [comment]
For 2. we could try basing it off of [SatFlows](https://github.com/openclimatefix/satflow/blob/main/.github/workflows/docker.yaml) which publishes to Docker Hub and GitHub Container Repo on every push

**Comment by peterdudfield** [comment]
I'll put the auto make docker image in a new issue - https://github.com/openclimatefix/nowcasting_api/issues/7

**Comment by peterdudfield** [comment]
@all-contributors please add @mdfaisal98  for code
