### ISSUE TITLE
Add test for floor_30_minutes_dt

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#5]
## Detailed Description
Add a few tests to make sure 'floor_30_minutes_dt' is working corectly. 

## Context
This is needed in order to find the rounded down half an hour, when querying the api for the latest forecast

## Possible Implementation
see other test structure

**Comment by BodaleDenis** [comment]
Hi, I'm new to contributing and I like this proposal so I would like to help if it's OK.
I think I should be assigned to it ? 😁

**Comment by peterdudfield** [comment]
Thanks @BodaleDenis , that would be so great if you can help out - thanks

**Comment by peterdudfield** [comment]
It would be great to test edge cases, i.e what happens when the date time is already floored to 30 mins, i.e 16:30:00 e.t.c

**Comment by peterdudfield** [comment]
Small extra task, would be great to add one other example that shows it explicity 

i.e
in = datetime.fromisoformat('2019-01-01 12:15:05') out = datetime.fromisoformat('2019-01-01 12:00:00') assert floor_30_minutes_dt(in) == out

**Comment by peterdudfield** [comment]
@all-contributors please add @BodaleDenis for code
