### ISSUE TITLE
Return Shape as GeoJSON instead of String

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/nowcasting_api#69]
`/v0/forecasts/GB/pv/gsp_boundaries` currently returns the response as a string.
It would be better to return it as a JSON instead.

**Comment by peterdudfield** [comment]
hmmm, im not quite sure how to do that. 

[I have a 'geoDataFrame' and i use to_json to put it to a json object. ](https://github.com/openclimatefix/nowcasting_api/blob/main/src/main.py#L92)
[
Admittedly, all respsonse need response.json() to get the object. ](https://github.com/openclimatefix/nowcasting_api/blob/main/src/tests/test_main.py#L72)

Is json normally a string, but just the string is ~ like a dictionary - https://www.w3schools.com/python/python_json.asp

**Comment by flowirtz** [comment]
I just had another look.

So currently the endpoint for the GSP shapes returns this:
```json
"{\"key\": \"value\"}"
```

But typically, with REST APIs, it would be good to return the JSON directly, instead of the string escaped version, ie
```json
{"key": "value"}
```

---

[geopandas.GeoDataFrame.to_json](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_json.html#geopandas-geodataframe-to-json) seems to return the JSON as string, as per the docs. I'd suggest that instead we try to return the dict directly, ie

`to_json()` -> `to_dict()`

https://github.com/openclimatefix/nowcasting_api/blob/96d8e46608e4ac9edcfea38918165ea41e43f3da/src/main.py#L92

[According to FastAPIs docs](https://fastapi.tiangolo.com/advanced/response-directly/#return-a-response-directly), they would convert that dict into JSON automatically.


I wasn't able to get the API running locally, so I couldn't try it myself yet.

**Comment by peterdudfield** [comment]
Cool ill do this - thanks for looking into this @flowirtz. 

Im interested what error you got when you ran it locally?

**Comment by flowirtz** [comment]
Fantastic, thanks so much, Peter! I don't remember anymore tbh, but I'll try running it again later this week and debug together with you :)
