### ISSUE TITLE
Add route GSP capacity

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#90]
## Detailed Description
Get GSP capacity details

## Context
This is so we can show the % of power being generated

## Possible Implementation
provide list of `GSPSystems`. Need to add capacity to GSP systems  in the data model, and update GSP consumer to load capacity

**Comment by JackKelly** [comment]
BTW, I _think_ I've seen times when the PV Live reported generation for a GSP region can be a little _higher_ (!) than the reported capacity! So the "percentage of capacity" might sometimes be _above_ 100%! I'm not sure what the correct fix is. Other than maybe to take the capacity as that max of `recent reported power` and `reported capacity`?

**Comment by peterdudfield** [comment]
hmm tricky one. 
1. we could when pulling the GSP level data, check if max power is > capacity, and then update capacity accordingly. I'm a bit worried by that, as it seems a bit complicated, and maybe a large power error could cause an issue here. 
2. run a `montly` job to make sure capacity is always updated to the most recent values

Perhaps lets re visit it if it comes up again.

**Comment by JackKelly** [comment]
yeah, I agree, let's revisit this later :)

For now, for the UI, it's maybe sufficient just for the UI to clip the "proportion" at 100%.
