### ISSUE TITLE
Speed up normalize route

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_api#99]
## Detailed Description
Current the [/v0/GB/solar/gsp/forecast/all](http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs#/default/get_all_available_forecasts_v0_GB_solar_gsp_forecast_all_get) with normalize == True takes ~10 seconds. This is to long. 

## Context
Would be good for FE if ~1 second

## Possible Implementation
slow part is the looping in the pydantic model, to normalize data. We could:
- Save the data and add a 'normalize' flag. This would double the amount of data in the database, but make for quick reading
- Paralize the processing - [here](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/models/models.py#L239). Not sure if setup up parrallel costs would make it speed up
- Try to convert pydantic models to flat pandas frames, then operate on one column, then convert back to pydantic models
- Add validation method to pydanitc model, use if normalize do this. 
- Other options ...

**Comment by JackKelly** [comment]
I'm not familiar with the code but is there a way to vectorise the normalization? (Maybe that's what converting to `pd.DataFrame` would achieve?)

**Comment by peterdudfield** [comment]
On version 0.1.34

normalize = false took 2.77 seconds
normalize= True took 2.87 seconds

So ill close this for now. They can be a case to speed this query up, but this is not to do with normalizing data or not

**Comment by peterdudfield** [comment]
> I'm not familiar with the code but is there a way to vectorise the normalization? (Maybe that's what converting to `pd.DataFrame` would achieve?)

yea, that would be the aim. Unfortunately the slowest is by the database, probably the thing to do is this - https://github.com/openclimatefix/nowcasting_datamodel/issues/2
